
name : push

on :
  push :
    branches : [ master ]

jobs :

  Cancel:
    if : "!startsWith( github.event.head_commit.message, 'version' )"
    name : 'Cancel Previous Runs'
    runs-on : ubuntu-latest
    timeout-minutes : 1
    steps :
      - uses : styfle/cancel-workflow-action@0.4.0
        with :
          access_token : ${{ github.token }}
          # workflow_id : ${{ github.workflow }}

  Fast :
    if : "!startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest ]
        node-version : [ 14.x ]
    steps :
    - run : git config --global core.autocrlf input
    - run : git config --global user.email "testing@testing.com"
    - run : git config --global user.name "Testing"
    - uses : actions/checkout@v2
    - run : wget https://raw.githubusercontent.com/tomav/docker-mailserver/master/docker-compose.yml
    - run : wget https://raw.githubusercontent.com/tomav/docker-mailserver/master/mailserver.env
    - run : wget -O .env https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/ed7106b04d545be6320a6943bd4a367e8622c8d6/compose.env
    - run : docker-compose up -d mail
    - run : docker exec mail addmailuser user@domain.com password
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm i
    - name : npm test
      run : npm test
      env :
        WTOOLS_BOT_TOKEN : ${{ secrets.WTOOLS_BOT_TOKEN }}

